SELECT 
j.DATA_INICIO ,
j.DATA_FIM ,
j.TEMPO_IGNICAO_LIGADA IGN,
j.TEMPO_MOTOR_GIRANDO TMG,
j.TEMPO_MARCHA_LENTA TML,
j.TEMPO_FAIXA_IDEAL TFI,
j.TEMPO_MOVIMENTO TM,
j.QUILOMETROS_RODADOS KM,
i.IMEI ,
--v.VEHICLE_PREFIX PREFIX,
--J.VEHICLE_ID ,
--j.ERROR_ID ,
j.HODOMETRO_INICIO ,
j.HODOMETRO_FIM ,
j.LITROMETRO_INICIO ,
j.LITROMETRO_FIM ,
--(j.LITROMETRO_FIM-j.LITROMETRO_INICIO) Litros,
--(j.QUILOMETROS_RODADOS/(j.LITROMETRO_FIM-j.LITROMETRO_INICIO)) kml,
j.HORIMETRO_INICIO ,
j.HORIMETRO_FIM ,
--((j.HORIMETRO_FIM-j.HORIMETRO_INICIO)*60) horimetro,
(SELECT MAX(al.vel) FROM aero.AVL_LOCATIONS al WHERE al.DATE_HOUR BETWEEN j.DATA_INICIO AND j.DATA_FIM AND v.VEHICLE_ID = al.VEHICLE_ID) AS velMax,
(SELECT MAX(al.ROT) FROM aero.AVL_LOCATIONS al WHERE al.DATE_HOUR BETWEEN j.DATA_INICIO AND j.DATA_FIM AND v.VEHICLE_ID = al.VEHICLE_ID) AS ROTMax,
v.VEHICLE_PLATES PLACA,
--v.VEHICLE_ID ,
--v.customer_child_id,
v.DESCRIPTION ,
cc.MATRIZ 
FROM AERO.JOURNEY j 
join aero.vehicles v on v.vehicle_id=j.vehicle_id 
JOIN AERO.ACTIVE_CUSTOMERS_HIERARCHY cc on cc.customer_child_id = v.customer_child_id
JOIN AERO.VEHICLE_IMEI i on i.VEHICLE_ID=v.VEHICLE_ID 
WHERE 1=1
--AND v.VEHICLE_PREFIX ='H085A'
AND DATA_INICIO > sysdate -30
--and cc.customer_id=4345
--AND TEMPO_MOTOR_GIRANDO < (TEMPO_MARCHA_LENTA + TEMPO_FAIXA_IDEAL)
and  v.VEHICLE_PLATES  like (  '92026' )
--AND (j.LITROMETRO_FIM-j.LITROMETRO_INICIO) <> 0
--AND j.TEMPO_IGNICAO_LIGADA  > '1000'
--AND i.IMEI LIKE 'VIRLOC10_D386'
--AND v.DESCRIPTION LIKE '%3344%'
--and UPPER(cc.matriz) like '%SUZANO%'
--AND j.VEHICLE_ID IN ('520979')
--AND j.DATA_INICIO = j.DATA_FIM 
--AND j.LITROMETRO_INICIO < '4278190.5'
ORDER BY j.ID desc

SELECT * FROM AERO.VEHICLE_IMEI_HISTORY vih 

SELECT * FROM aero.IMEI_HISTORY

SELECT * FROM AERO.VEHICLES_HISTORY vh  

SELECT * FROM AERO.CONFIG_VIRTEC_PARAMETERS cvp 
--WHERE CUSTOMER_PROFILE_VERSION = 'CELUL_MS.210518'
WHERE ADITIONAL_SCRIPT_VERSION LIKE 'M%'

SELECT * FROM aero.ERRORS e 

SELECT * FROM aero.ACTIVE_CUSTOMERS ac 
WHERE UPPER(CUSTOMER_CHILD_NAME) LIKE '%CTEEP%' 

SELECT * FROM AERO.JOURNEY 
WHERE VEHICLE_ID IN ('508118')