SELECT * FROM AERO.CONFIG_00273 c 
WHERE VEHICLE_ID ='544977'
ORDER BY DATA_HORA DESC


SELECT * FROM AERO.EVENTS_GROUPS eg 


(SELECT 
V.CUSTOMER_CHILD_ID , VEHICLE_ID , VEHICLE_TYPE , VEHICLE_PLATES , VEHICLE_PREFIX , CC.MATRIZ ,CC.FILIAL , CC.REGIONAL , CC.HIERARQUIA , eg.EVENT_GROUP_ID , eg.EVENT_GROUP_NAME , eg.STATUS 
FROM AERO.VEHICLES V 
JOIN AERO.Active_Customers_Hierarchy CC ON V.CUSTOMER_CHILD_ID = CC.CUSTOMER_CHILD_ID 
JOIN AERO.EVENTS_GROUPS eg ON eg.CUSTOMER_CHILD_ID = V.CUSTOMER_CHILD_ID 
WHERE VEHICLE_STATUS=1 
--AND CC.CUSTOMER_ID=31993 
AND VEHICLE_PLATES = 'GR01'
--And CC.FILIAL IN ('JSL GUAIBA/RS','JSL ARACRUZ/ES','JSL BELO ORIENTE/MG','JSL IMPERATRIZ/MA','JSL TELÊMACO BORBA/PR','JSL EUNAPOLIS/BA','JSL MINERAÇÃO SUL','JSL TURMALINA','JSL PETROBRAS','JSL SUCROALCOLEIRO','JSL PORTOCEL/ES','JSL INDIANOPOLIS/MG','JSL LENÇÓIS PAULISTA/SP') 
)

