SELECT 
--* 
DATA_HORA ,
VEHICLE_ID ,
v.VEHICLE_PLATES ,
CODIGO ,
TEMPO_EXCESSO ,
VELOCIDADE ,
VALOR_LIMITE_UTILIZADO ,
ROTACAO ,
it.DESCRICAO ,
VALOR_REGISTRADO 
FROM AERO.INFRACTION i 
JOIN AERO.INFRACTION_TYPE it USING(CODIGO)
JOIN aero.VEHICLES v USING (vehicle_id)
WHERE VEHICLE_ID = '534122'
ORDER BY i.id desc




SELECT * FROM AERO.INFRACTION_TYPE it 