DECLARE
TYPE resultT IS RECORD(
VID INTEGER
);
TYPE ARR IS TABLE OF resultT;
mArr ARR;
BEGIN
select * bulk COLLECT into mArr from
(
--EMPRESA QULQUER
--SELECT VEHICLE_ID FROM VEHICLES WHERE CUSTOMER_CHILD_ID=20436 AND VEHICLE_STATUS=1
-- TODAS GRUAS DA FIBRIA
--(SELECT VEHICLE_ID FROM VEHICLES V JOIN Active_Customers_Hierarchy CC USING(CUSTOMER_CHILD_ID) WHERE CUSTOMER_ID=3979 AND VEHICLE_STATUS=1 AND Vehicle_Type=16)
-- TODAS MADEREIROS MS/SP DA FIBRIA
(SELECT VEHICLE_ID FROM AERO.VEHICLES V JOIN AERO.Active_Customers_Hierarchy CC USING(CUSTOMER_CHILD_ID) WHERE VEHICLE_STATUS=1 AND CUSTOMER_ID=5263 And CC.FILIAL IN ('JSL GUAIBA/RS','JSL ARACRUZ/ES','JSL BELO ORIENTE/MG','JSL IMPERATRIZ/MA','JSL TELÊMACO BORBA/PR','JSL EUNAPOLIS/BA','JSL MINERAÇÃO SUL','JSL TURMALINA','JSL PETROBRAS','JSL SUCROALCOLEIRO','JSL PORTOCEL/ES','JSL INDIANOPOLIS/MG','JSL LENÇÓIS PAULISTA/SP') AND Vehicle_Type = 17)
--(SELECT VEHICLE_ID FROM AERO.VEHICLES V JOIN AERO.Active_Customers_Hierarchy CC USING(CUSTOMER_CHILD_ID) WHERE VEHICLE_STATUS=1 AND CUSTOMER_ID=5263 And CC.FILIAL IN ('JSL GUAIBA/RS') AND Vehicle_Type = 17)
---- TODAS MADEREIROS GAFOR ES DA FIBRIA
--(SELECT VEHICLE_ID FROM VEHICLES V JOIN Active_Customers_Hierarchy CC USING(CUSTOMER_CHILD_ID) WHERE VEHICLE_STATUS=1 AND CUSTOMER_ID=3979 And CC.REGIONAL IN ('Gafor - ES') AND Vehicle_Type = 17)
-- TODAS MADEREIROS GAFOR ES DA FIBRIA
--(SELECT VEHICLE_ID FROM VEHICLES V JOIN Active_Customers_Hierarchy CC USING(CUSTOMER_CHILD_ID) WHERE VEHICLE_STATUS=1 AND MATRIZ='Cenibra' And CC.FILIAL IN ('JSL BELO ORIENTE/MG') AND Vehicle_Type = 17)
);
begin
forall indexIns in 1 .. mArr.count insert into aero.config_00273 (VEHICLE_ID,DATA_HORA,COD_EVENTO,MSG_EVENTO,EVENT_GROUP_ID,ROTULO,COD_NUM,TIPO,ENTRADA_DADOS,INDICE,CLASSE,INPUT,IS_CRITICAL) values (mArr(indexIns).VID,SYSDATE,1091,'CARONA',500,'MOTORISTA',0,0,'0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0',0,'0;0;0;0;0;0;0;0;0;0','000',0);
forall indexIns in 1 .. mArr.count insert into aero.config_00273 (VEHICLE_ID,DATA_HORA,COD_EVENTO,MSG_EVENTO,EVENT_GROUP_ID,ROTULO,COD_NUM,TIPO,ENTRADA_DADOS,INDICE,CLASSE,INPUT,IS_CRITICAL) values (mArr(indexIns).VID,SYSDATE,1092,'CARONA',500,'MOTORISTA',0,0,'0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0',0,'0;0;0;0;0;0;0;0;0;0','000',0);
forall indexIns in 1 .. mArr.count insert into aero.config_00273 (VEHICLE_ID,DATA_HORA,COD_EVENTO,MSG_EVENTO,EVENT_GROUP_ID,ROTULO,COD_NUM,TIPO,ENTRADA_DADOS,INDICE,CLASSE,INPUT,IS_CRITICAL) values (mArr(indexIns).VID,SYSDATE,1094,'CARONA',500,'MOTORISTA',0,0,'0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0',0,'0;0;0;0;0;0;0;0;0;0','000',0);
COMMIT;
exception
when others then
ROLLBACK;
SYS.DBMS_OUTPUT.put_line('falhou');
RAISE;
end;
SYS.DBMS_OUTPUT.put_line('sucesso..');
END;