begin
for i in
(
select
cc.matriz,
cc.filial,
cc.regional,
cc.unidade,
v.vehicle_id,
v.description as modelo,
V.Vehicle_Year As Ano,
v.vehicle_plates as placa,
v.vehicle_prefix as prefixo,
v.embeded_fences_limit,
regexp_replace(i.imei,'_\w+','') equip,
regexp_replace(i.imei,'\w+_','') did
from aero.vehicles v
left join aero.vehicle_imei i on i.vehicle_id=v.vehicle_id
left join aero.active_customers_hierarchy cc on cc.customer_child_id = v.customer_child_id
where v.vehicle_status in (1)
--and UPPER(cc.matriz) like '%CPFL%'
--AND I.IMEI LIKE 'VIRLOC8_%'
and v.vehicle_plates in ('EXL9II8','QON2D16','OQJ4721','RND8A37','FDC7264','OXC0I92','PPZ7G29','QOM9J48','GDT4384','CM048','PTM5071','PLP8C30','PLX9F10','IZT3G08','QVY4G92','PTM8463','IZT3F61','QOH1A24','BDF4D32','PTM4357','PLX0B53')
--AND v.VEHICLE_PREFIX IN ('000175','000184','000179','000192')
)
loop
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1905');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1906');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED22');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED23');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED202');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QTR15');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SED22 IN07++ +- GFA AX {QUV00,9,33 QCT01,7,10 QCT02,7,10 QCT00,7,10 QCT85,7,5}');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SED23 IN07-- +- GFA AX {QUV00,9,33 QCT01,7,10 QCT02,7,10 QCT00,7,10 QCT85,7,5}');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'VQRT2');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'VQRT3');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QUT19');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED008');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED009');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED010');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED011');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED012');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED013');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED015');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED016');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED017');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED022');
--insert into AERO.HW_VIRLOC6_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED191');
end loop;
end;
