
begin
for i in
(
select
cc.matriz,
cc.filial,
cc.regional,
cc.unidade,
v.vehicle_id,
v.description as modelo,
V.Vehicle_Year As Ano,
v.vehicle_plates as placa,
v.vehicle_prefix as prefixo,
v.embeded_fences_limit,
regexp_replace(i.imei,'_\w+','') equip,
regexp_replace(i.imei,'\w+_','') did
from aero.vehicles v
left join aero.vehicle_imei i on i.vehicle_id=v.vehicle_id
left join aero.active_customers_hierarchy cc on cc.customer_child_id = v.customer_child_id
where v.vehicle_status in (1)
--and UPPER(cc.matriz) like '%BRACELL%'
AND I.IMEI LIKE 'VIRLOC10_%'
--AND v.DESCRIPTION LIKE '%3344'
AND regexp_replace(i.imei,'\w+_','') IN ('5368','5C9F','9388','9305')
--and v.vehicle_plates in ('QPW3257','FQO5H43','DVC9H83','CUI8C78','FPI4B25','FDP1F98','BSY2F46','DMN6C07','FRO8F25','QIX-5171','FVT6J65','FNM4H42','FOV3D35','BYQ7H08','QIX-4861','FIL5J21','FCD4J32','CPN0I17','EEM4I62','BTY4E51','CUL0F93','CCX6G21','QIX-2561')
)
loop
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'VS2902,1702,0,11,81,1,4,FFFFFFFF,0,0,1000');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED23');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED22');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'VQ2902');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'VQ2905');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'VS2905,65257,0,29,81,5,4,FFFFFFFF,0,0,1000');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'VS2905_MAT,x5H4000000');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'VS2902,1702,0,11,81,1,4,FFFFFFFF,0,0,1000');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SED23 IN07-- +- GF0 AX {QUV00,9,33 QCT01,7,10 QCT02,7,10 QCT81,7,10 QCT85,7,5}');
--insert into AERO.HW_VIRLOC8_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SED22 SG00++ +- GF0 AX {QUV00,9,33 QCT01,7,10 QCT02,7,10 QCT81,7,10 QCT85,7,5}');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SED37 TT00++ UC15--||UC03--||IN01++&&SG04++ GF0 V8 {SCT50 VCT70+VCT04}{SCT5153 0}{SSH040}');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SBA2071 SUT14,QCT81,7,10,0,800000');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SBA2072 SED127 TT00++ IN07++&&UC14++ SGN NN {SCT50 VCT81*10/2}{GGRVCT50VCT00}{SCT00 VCT50}');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SBA2073 SCT00 0');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SBA2074 SED45U');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SBA2075');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SED45 IN07-- +- SGN NN {SBA_RUN2071}');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'S1907,65262,80,1,1,000000FF,0,29,000,0');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'S1908,65263,82,4,1,FFFFFFFF,0,29,000,0');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'STD120120');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'SED45 TD12++&&IN07++ +- GR0 AX {QCT80,1,99 QCT82,1,99}');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1900');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1901');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1902');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1903');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1904');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1905');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1906');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED213');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED214');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED211');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED203');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'QED119');
insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1907');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1908');
--insert into AERO.HW_VIRLOC10_OUTBOX (DEVICE_ID, PRIORITY_TRANSMIT, DELIVERY_LEVEL, MODIFIER, MESSAGE) values (i.did,0,2,null,'Q1909');

end loop;
end;







