SELECT 
*
FROM aero.VEHICLES V
JOIN aero.VEHICLE_IMEI VI ON V.VEHICLE_ID = VI.VEHICLE_ID
WHERE VEHICLE_TYPE = '17'
AND VI.CUSTOMER_CHILD_ID = '21434'

SELECT * 
FROM AERO.CUSTOMER_CHILD 
WHERE CUSTOMER_CHILD_NAME LIKE '%JSL AGRO'

SELECT *
FROM AERO.ACTIVE_CUSTOMERS_HIERARCHY ach 
WHERE MATRIZ LIKE 'JSL AGRO'
--AND CUSTOMER_CHILD_ID = '29046'



--INFRAÇOES SIRTEC
SELECT 
*
FROM aero.INFRACTION i 
JOIN aero.INFRACTION_TYPE it ON it.CODIGO = i.CODIGO 
WHERE VEHICLE_ID = '507526' 
--AND it.CODIGO = '4105'
ORDER BY DATA_HORA DESC


