SELECT
PLACA,
VEHICLE_ID,
AC.MATRIZ,
V.CUSTOMER_CHILD_ID,
EQUIP_ATUAL,
V.v_mbtype_id,
DECODE(EQUIP_ATUAL,'G5',31,'G3',34) MB_TYPE,
V.COST_CENTRE,
CENTRO_DE_CUSTO,
'UPDATE AERO.VEHICLES SET v_mbtype_id='||DECODE(EQUIP_ATUAL,'G5',31,'G3',34)||' WHERE vehicle_id='||VEHICLE_ID||';',
'UPDATE AERO.VEHICLES SET COST_CENTRE='''||CENTRO_DE_CUSTO||''' WHERE vehicle_id='||VEHICLE_ID||';'
FROM atualizacao_vale AV
LEFT JOIN AERO.VEHICLES V ON REPLACE(V.VEHICLE_PLATES,'-','') = AV.PLACA
LEFT JOIN AERO.active_customers_hierarchy AC ON V.CUSTOMER_CHILD_ID=AC.CUSTOMER_CHILD_ID
WHERE MATRIZ = 'Vale S.A (Focus)'
AND V.VEHICLE_STATUS=1
AND V.VEHICLE_PLATES LIKE '%-%'
;